### PR TITLE
Add ability to use mongodb to store data

### PR DESCRIPTION
**Pull request by joepalomino**
@jparker3 when you pull this down there will some steps:

1.  installing mongodb with homebrew
2. creating a data folder in the picklebot dir
3. starting mongo with the path to that folder
4. creating the name of the db
5. setting a mongo uri environment var

boom and then it should work!

### CODE REVIEW

**Comment by joepalomino** [comment]
[The bot server will use a database to store a teams game order](https://trello.com/c/Q0rGreZ7/12-the-bot-server-will-use-a-database-to-store-a-teams-game-order)

**Comment by jparker3** [comment]
Everything looks great! Create a ReadMe file with the instructions above to set up Mongodb.

**Comment by joepalomino** [comment]
no

**Comment by jparker3** [comment]
fine

**Pull request merged**
